### ISSUE TITLE
Add Brian to team list

### ISSUE THREAD

**Issue by carver** [ethereum/trinity-web#3]
I think @lithp could be added to this team list (if he wants):
https://trinity.ethereum.org/#team

This should probably build on top of #2 to avoid conflicts.

**Comment by pipermerriam** [comment]
@lithp need a headshot that is compatible with the existing image dimensions from you and then we need to apply whatever *filter* is needed to make it all blue-ey like the other ones.  Wonder if we have a designer in-house that can do that.
